/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package model;

/**
 *
 * @author tallesventura
 */
public enum Token {

//    ABRE_CHAVES, ABRE_COLCHETES, ABRE_PARENTESES, AND, AND_BINARIO, AS, ASPAS_DUPLAS, ASPAS_SIMPLES, ASYNC, BREAK, CLASS,  COMPLEMENTO_DE_UM, CONTINUE,
//    DEDENT, DEF, DELETE, DOIS_PONTOS, ELIF, ELSE, ERROR, EXCEPT, OP_EXPONENCIACAO, OP_EXPONENCIACAO_IGUAL,
//    FALSE, FECHA_CHAVES, FECHA_COLCHETES, FECHA_PARENTESES, FOR, FROM, GLOBAL, IDENTIFICADOR, IF, IMPORT, IN, IS, LEFT_SHIFT, NONE, NONLOCAL, NOT, NOVA_LINHA, 
//    NUMERO, OP_ADICAO, OP_AND_IGUAL, OP_ARROBA, OP_ARROBA_IGUAL, OP_ATRIBUICAO, OP_CIRCUNFLEXO_IGUAL, OP_DIFERENTE, OP_DIVIDIDO_IGUAL, OP_DIVISAO, OP_DIVISAO_INTEIRA, 
//    OP_DIVISAO_INTEIRA_IGUAL, OP_IGUALDADE, OP_LEFT_SHIFT_IGUAL, OP_MAIOR, OP_MAIOR_IGUAL, OP_MAIS_IGUAL, OP_MENOR, OP_MENOR_IGUAL,
//    OP_MENOS_IGUAL, OP_MULTIPLICACAO, OP_NEGACAO, OP_OR_IGUAL, OP_RESTO, OP_RESTO_IGUAL, OP_RIGHT_SHIFT_IGUAL, OP_SUBTRACAO, OP_TIL, OP_VEZES_IGUAL, 
//    OR, OR_BINARIO, OR_EXCLUSIVO_BINARIO, PASS, PONTO, PONTO_VIRGULA, PRINT, RAISE, RANGE, RETURN, RIGHT_SHIFT, STRING, TRUE, TRY, VIRGULA, WHILE, YIELD,
//    INTEIRO, REAL,
    
        
    // Palavras reservadas
    PC_PROGRAMA, PC_INICIO, PC_FIM, PC_VARIAVEL, PC_CONSTANTE, PC_SE, 
    PC_ENTAO, PC_SENAO, PC_ENQUANTO, PC_FACA, PC_REPITA, PC_ATE_QUE, PC_PARA, PC_ATE,
    PC_INTEIRO, PC_REAL, PC_STRING, PC_CHAR, PC_BOOLEANO,
    PC_LEIA, PC_ESCREVA,
    
    
    // Pontuacao
    PONTO, VIRGULA, DOIS_PONTOS, PONTO_VIRGULA, ASPAS_SIMPLES, ABRE_PARENTESES, FECHA_PARENTESES,
    
    // Operadores relacionais
    OP_IGUAL, OP_DIFERENTE, OP_MAIOR, OP_MENOR, OP_MAIOR_IGUAL, OP_MENOR_IGUAL,
    
    // Operadores aritmeticos
    OP_ADICAO, OP_SUBTRACAO, OP_MULTIPLICACAO, OP_DIVISAO,
    
    // Operadores de atribuicao
    OP_ATRIBUICAO,
    
    // Operadores logicos
    OP_E, OP_OU, OP_NAO,
    
    // Padroes
    IDENTIFICADOR, INTEIRO, REAL,
    
}
