/* The following code was generated by JFlex 1.6.1 */

package analisador_lexico;

import model.Token;
import model.TokenModel;



/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.1
 * from the specification file <tt>C:/Users/Jefferson/Desktop/Nova pasta/compilador-portugol/src/main/java/analisador_lexico/Lexer.flex</tt>
 */
public class Lexer {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\1\1\1\1\50\1\50\1\50\22\0\1\44\6\0\1\11"+
    "\1\12\1\13\1\16\1\14\1\6\1\15\1\5\1\17\1\3\11\4"+
    "\1\7\1\10\1\26\1\25\1\27\2\0\32\2\6\0\1\24\1\46"+
    "\1\35\1\47\1\20\1\36\1\32\1\45\1\34\2\2\1\40\1\33"+
    "\1\23\1\21\1\30\1\43\1\31\1\41\1\42\1\22\1\37\4\2"+
    "\1\0\1\1\10\0\1\50\u1fa2\0\1\50\1\50\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\udfe6\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\1\1\2\1\3\1\1\2\4\1\5\1\6\1\7"+
    "\1\10\1\11\1\12\1\13\1\14\1\15\1\16\1\17"+
    "\1\20\3\1\1\21\1\22\1\23\11\1\2\0\1\24"+
    "\2\1\1\25\2\1\1\26\1\27\1\30\13\1\1\31"+
    "\2\1\1\32\3\1\1\33\1\34\12\1\1\35\11\1"+
    "\1\0\1\36\1\1\1\37\4\1\1\40\1\41\3\1"+
    "\1\42\3\1\1\43\2\1\1\0\5\1\1\44\2\1"+
    "\1\45\4\1\1\0\1\1\1\46\1\47\4\1\1\50"+
    "\2\1\1\51\1\52\1\1\1\53\4\1\1\54\1\55"+
    "\2\1\1\56\1\57\1\60\1\1\1\61";

  private static int [] zzUnpackAction() {
    int [] result = new int[146];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\51\0\51\0\122\0\173\0\244\0\51\0\51"+
    "\0\315\0\51\0\51\0\51\0\51\0\51\0\51\0\51"+
    "\0\51\0\366\0\u011f\0\u0148\0\u0171\0\51\0\u019a\0\u01c3"+
    "\0\u01ec\0\u0215\0\u023e\0\u0267\0\u0290\0\u02b9\0\u02e2\0\u030b"+
    "\0\u0334\0\173\0\u035d\0\51\0\u0386\0\u03af\0\122\0\u03d8"+
    "\0\u0401\0\51\0\51\0\51\0\u042a\0\u0453\0\u047c\0\u04a5"+
    "\0\u04ce\0\u04f7\0\u0520\0\u0549\0\u0572\0\u059b\0\u05c4\0\u05ed"+
    "\0\u0616\0\u063f\0\u035d\0\u0668\0\u0691\0\u06ba\0\122\0\u06e3"+
    "\0\u070c\0\u0735\0\u075e\0\u0787\0\u07b0\0\u07d9\0\u0802\0\u082b"+
    "\0\u0854\0\u087d\0\122\0\u08a6\0\u08cf\0\u08f8\0\u0921\0\u094a"+
    "\0\u0973\0\u099c\0\u09c5\0\u09ee\0\u0a17\0\122\0\u0a40\0\122"+
    "\0\u0a69\0\u0a92\0\u0abb\0\u0ae4\0\122\0\122\0\u0b0d\0\u0b36"+
    "\0\u0b5f\0\122\0\u0b88\0\u0bb1\0\u0bda\0\122\0\u0c03\0\u0c2c"+
    "\0\u0c55\0\u0c7e\0\u0ca7\0\u0cd0\0\u0cf9\0\u0d22\0\122\0\u0d4b"+
    "\0\u0d74\0\122\0\u0d9d\0\u0dc6\0\u0def\0\u0e18\0\u0e41\0\u0e6a"+
    "\0\122\0\122\0\u0e93\0\u0ebc\0\u0ee5\0\u0f0e\0\122\0\u0f37"+
    "\0\u0f60\0\122\0\51\0\u0f89\0\122\0\u0fb2\0\u0fdb\0\u1004"+
    "\0\u102d\0\122\0\122\0\u1056\0\u107f\0\122\0\122\0\122"+
    "\0\u10a8\0\122";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[146];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\1\7\1\10\1\11"+
    "\1\12\1\13\1\14\1\15\1\16\1\17\1\20\1\21"+
    "\1\22\1\23\1\4\1\24\1\25\1\26\1\27\1\30"+
    "\1\31\1\32\2\4\1\33\1\34\1\35\1\36\1\37"+
    "\1\40\2\4\1\3\1\4\1\41\1\4\54\0\1\4"+
    "\15\0\5\4\3\0\14\4\1\0\3\4\4\0\2\42"+
    "\1\43\46\0\2\6\1\43\70\0\1\44\25\0\1\4"+
    "\15\0\3\4\1\45\1\4\3\0\11\4\1\46\2\4"+
    "\1\0\3\4\3\0\1\4\15\0\2\4\1\47\2\4"+
    "\3\0\14\4\1\0\3\4\3\0\1\4\15\0\4\4"+
    "\1\50\3\0\14\4\1\0\3\4\3\0\1\4\15\0"+
    "\5\4\3\0\12\4\1\51\1\4\1\0\3\4\26\0"+
    "\1\52\1\0\1\53\46\0\1\54\25\0\1\4\15\0"+
    "\4\4\1\55\3\0\1\4\1\56\12\4\1\0\3\4"+
    "\3\0\1\4\15\0\1\57\4\4\3\0\14\4\1\0"+
    "\3\4\3\0\1\4\15\0\3\4\1\60\1\4\3\0"+
    "\14\4\1\0\3\4\3\0\1\4\15\0\1\4\1\61"+
    "\3\4\3\0\14\4\1\0\1\62\2\4\3\0\1\4"+
    "\15\0\4\4\1\63\3\0\4\4\1\64\7\4\1\0"+
    "\3\4\3\0\1\4\15\0\1\65\3\4\1\66\3\0"+
    "\14\4\1\0\3\4\3\0\1\4\15\0\1\67\4\4"+
    "\3\0\14\4\1\0\3\4\3\0\1\4\15\0\1\70"+
    "\4\4\3\0\12\4\1\71\1\4\1\0\3\4\3\0"+
    "\1\4\15\0\1\4\1\72\3\4\3\0\14\4\1\0"+
    "\3\4\4\0\2\73\46\0\1\4\15\0\5\4\3\0"+
    "\12\4\1\74\1\75\1\0\3\4\3\0\1\4\15\0"+
    "\5\4\3\0\5\4\1\76\6\4\1\0\3\4\3\0"+
    "\1\4\15\0\1\4\1\77\3\4\3\0\14\4\1\0"+
    "\3\4\3\0\1\4\15\0\1\100\4\4\3\0\14\4"+
    "\1\0\3\4\3\0\1\4\15\0\5\4\3\0\1\4"+
    "\1\101\12\4\1\0\3\4\3\0\1\4\15\0\1\4"+
    "\1\102\3\4\3\0\14\4\1\0\3\4\3\0\1\4"+
    "\15\0\4\4\1\103\3\0\1\104\13\4\1\0\3\4"+
    "\3\0\1\4\15\0\5\4\3\0\4\4\1\105\5\4"+
    "\1\106\1\4\1\0\3\4\3\0\1\4\15\0\3\4"+
    "\1\107\1\4\3\0\14\4\1\0\3\4\3\0\1\4"+
    "\15\0\4\4\1\110\3\0\14\4\1\0\3\4\3\0"+
    "\1\4\15\0\5\4\3\0\5\4\1\111\2\4\1\112"+
    "\3\4\1\0\3\4\3\0\1\4\15\0\5\4\3\0"+
    "\3\4\1\113\10\4\1\0\3\4\3\0\1\4\15\0"+
    "\5\4\3\0\1\4\1\114\12\4\1\0\3\4\3\0"+
    "\1\4\15\0\5\4\3\0\1\4\1\115\12\4\1\0"+
    "\3\4\3\0\1\4\15\0\5\4\3\0\4\4\1\116"+
    "\7\4\1\0\3\4\3\0\1\4\15\0\3\4\1\117"+
    "\1\4\3\0\14\4\1\0\3\4\3\0\1\4\15\0"+
    "\5\4\3\0\1\4\1\120\12\4\1\0\3\4\3\0"+
    "\1\4\15\0\1\4\1\121\3\4\3\0\14\4\1\0"+
    "\3\4\3\0\1\4\15\0\4\4\1\122\3\0\14\4"+
    "\1\0\3\4\3\0\1\4\15\0\2\4\1\123\2\4"+
    "\3\0\14\4\1\0\3\4\3\0\1\4\15\0\5\4"+
    "\3\0\1\4\1\124\12\4\1\0\3\4\3\0\1\4"+
    "\15\0\5\4\3\0\14\4\1\125\3\4\3\0\1\4"+
    "\15\0\4\4\1\126\3\0\14\4\1\0\3\4\3\0"+
    "\1\4\15\0\5\4\3\0\2\4\1\127\11\4\1\0"+
    "\3\4\3\0\1\4\15\0\5\4\3\0\10\4\1\130"+
    "\3\4\1\0\3\4\3\0\1\4\15\0\5\4\3\0"+
    "\4\4\1\131\7\4\1\0\3\4\3\0\1\4\15\0"+
    "\5\4\3\0\5\4\1\132\6\4\1\0\3\4\3\0"+
    "\1\4\15\0\1\133\4\4\3\0\14\4\1\0\3\4"+
    "\3\0\1\4\15\0\5\4\3\0\11\4\1\134\2\4"+
    "\1\0\3\4\3\0\1\4\15\0\5\4\3\0\1\4"+
    "\1\135\12\4\1\0\3\4\3\0\1\4\15\0\4\4"+
    "\1\136\3\0\14\4\1\0\3\4\3\0\1\4\15\0"+
    "\5\4\3\0\11\4\1\137\2\4\1\0\3\4\3\0"+
    "\1\4\15\0\5\4\3\0\14\4\1\0\2\4\1\140"+
    "\3\0\1\4\15\0\5\4\3\0\4\4\1\141\7\4"+
    "\1\0\3\4\3\0\1\4\15\0\4\4\1\142\3\0"+
    "\14\4\1\0\3\4\3\0\1\4\15\0\4\4\1\143"+
    "\3\0\14\4\1\0\3\4\3\0\1\4\15\0\5\4"+
    "\3\0\4\4\1\144\7\4\1\0\3\4\3\0\1\4"+
    "\15\0\5\4\3\0\10\4\1\145\3\4\1\0\3\4"+
    "\3\0\1\4\15\0\1\4\1\146\3\4\3\0\14\4"+
    "\1\0\3\4\3\0\1\4\15\0\4\4\1\147\3\0"+
    "\14\4\1\0\3\4\3\0\1\4\15\0\1\150\4\4"+
    "\3\0\14\4\1\0\3\4\44\0\1\151\7\0\1\4"+
    "\15\0\5\4\3\0\1\4\1\152\12\4\1\0\3\4"+
    "\3\0\1\4\15\0\5\4\3\0\12\4\1\153\1\4"+
    "\1\0\3\4\3\0\1\4\15\0\5\4\3\0\4\4"+
    "\1\154\7\4\1\0\3\4\3\0\1\4\15\0\5\4"+
    "\3\0\4\4\1\155\7\4\1\0\3\4\3\0\1\4"+
    "\15\0\5\4\3\0\12\4\1\156\1\4\1\0\3\4"+
    "\3\0\1\4\15\0\1\4\1\157\3\4\3\0\14\4"+
    "\1\0\3\4\3\0\1\4\15\0\4\4\1\160\3\0"+
    "\14\4\1\0\3\4\3\0\1\4\15\0\4\4\1\161"+
    "\3\0\14\4\1\0\3\4\3\0\1\4\15\0\1\4"+
    "\1\162\3\4\3\0\14\4\1\0\3\4\3\0\1\4"+
    "\15\0\3\4\1\163\1\4\3\0\14\4\1\0\3\4"+
    "\3\0\1\4\15\0\1\164\4\4\3\0\14\4\1\0"+
    "\3\4\3\0\1\4\15\0\3\4\1\165\1\4\3\0"+
    "\14\4\1\0\3\4\3\0\1\4\15\0\5\4\3\0"+
    "\7\4\1\166\4\4\1\0\3\4\23\0\1\167\30\0"+
    "\1\4\15\0\4\4\1\170\3\0\14\4\1\0\3\4"+
    "\3\0\1\4\15\0\4\4\1\171\3\0\14\4\1\0"+
    "\3\4\3\0\1\4\15\0\1\4\1\172\3\4\3\0"+
    "\14\4\1\0\3\4\3\0\1\4\15\0\5\4\3\0"+
    "\1\4\1\173\12\4\1\0\3\4\3\0\1\4\15\0"+
    "\4\4\1\174\3\0\14\4\1\0\3\4\3\0\1\4"+
    "\15\0\5\4\3\0\14\4\1\0\2\4\1\175\3\0"+
    "\1\4\15\0\5\4\3\0\7\4\1\176\4\4\1\0"+
    "\3\4\3\0\1\4\15\0\5\4\3\0\2\4\1\177"+
    "\11\4\1\0\3\4\3\0\1\4\15\0\4\4\1\200"+
    "\3\0\14\4\1\0\3\4\3\0\1\4\15\0\5\4"+
    "\3\0\12\4\1\201\1\4\1\0\3\4\3\0\1\4"+
    "\15\0\4\4\1\202\3\0\14\4\1\0\3\4\21\0"+
    "\1\203\32\0\1\4\15\0\5\4\3\0\3\4\1\204"+
    "\10\4\1\0\3\4\3\0\1\4\15\0\1\4\1\205"+
    "\3\4\3\0\14\4\1\0\3\4\3\0\1\4\15\0"+
    "\3\4\1\206\1\4\3\0\14\4\1\0\3\4\3\0"+
    "\1\4\15\0\1\207\4\4\3\0\14\4\1\0\3\4"+
    "\3\0\1\4\15\0\1\210\4\4\3\0\14\4\1\0"+
    "\3\4\3\0\1\4\15\0\3\4\1\211\1\4\3\0"+
    "\14\4\1\0\3\4\3\0\1\4\15\0\1\4\1\212"+
    "\3\4\3\0\14\4\1\0\3\4\3\0\1\4\15\0"+
    "\4\4\1\213\3\0\14\4\1\0\3\4\3\0\1\4"+
    "\15\0\5\4\3\0\12\4\1\214\1\4\1\0\3\4"+
    "\3\0\1\4\15\0\5\4\3\0\4\4\1\215\7\4"+
    "\1\0\3\4\3\0\1\4\15\0\5\4\3\0\10\4"+
    "\1\216\3\4\1\0\3\4\3\0\1\4\15\0\1\4"+
    "\1\217\3\4\3\0\14\4\1\0\3\4\3\0\1\4"+
    "\15\0\1\220\4\4\3\0\14\4\1\0\3\4\3\0"+
    "\1\4\15\0\5\4\3\0\1\4\1\221\12\4\1\0"+
    "\3\4\3\0\1\4\15\0\1\4\1\222\3\4\3\0"+
    "\14\4\1\0\3\4\1\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[4305];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\1\2\11\3\1\2\11\1\1\10\11\4\1\1\11"+
    "\13\1\2\0\1\11\5\1\3\11\50\1\1\0\23\1"+
    "\1\0\15\1\1\0\13\1\1\11\17\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[146];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */

private int id = 0;

private TokenModel createToken(int id, Token nome) {
    return new TokenModel(id, nome, yytext(), yyline, yycolumn);
}



  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 148) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public TokenModel yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
        return null;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { id+=1; return createToken(id, Token.IDENTIFICADOR);
            }
          case 50: break;
          case 2: 
            { throw new RuntimeException("Caractere inválido " + yytext() + " na linha " + yyline + ", coluna " +yycolumn);
            }
          case 51: break;
          case 3: 
            { /**/
            }
          case 52: break;
          case 4: 
            { id+=1; return createToken(id, Token.INTEIRO);
            }
          case 53: break;
          case 5: 
            { id+=1; return createToken(id, Token.PONTO);
            }
          case 54: break;
          case 6: 
            { id+=1; return createToken(id, Token.VIRGULA);
            }
          case 55: break;
          case 7: 
            { id+=1; return createToken(id, Token.DOIS_PONTOS);
            }
          case 56: break;
          case 8: 
            { id+=1; return createToken(id, Token.PONTO_VIRGULA);
            }
          case 57: break;
          case 9: 
            { id+=1; return createToken(id, Token.ASPAS_SIMPLES);
            }
          case 58: break;
          case 10: 
            { id+=1; return createToken(id, Token.ABRE_PARENTESES);
            }
          case 59: break;
          case 11: 
            { id+=1; return createToken(id, Token.FECHA_PARENTESES);
            }
          case 60: break;
          case 12: 
            { id+=1; return createToken(id, Token.OP_ADICAO);
            }
          case 61: break;
          case 13: 
            { id+=1; return createToken(id, Token.OP_SUBTRACAO);
            }
          case 62: break;
          case 14: 
            { id+=1; return createToken(id, Token.OP_MULTIPLICACAO);
            }
          case 63: break;
          case 15: 
            { id+=1; return createToken(id, Token.OP_DIVISAO);
            }
          case 64: break;
          case 16: 
            { id+=1; return createToken(id, Token.OP_E);
            }
          case 65: break;
          case 17: 
            { id+=1; return createToken(id, Token.OP_IGUAL);
            }
          case 66: break;
          case 18: 
            { id+=1; return createToken(id, Token.OP_MENOR);
            }
          case 67: break;
          case 19: 
            { id+=1; return createToken(id, Token.OP_MAIOR);
            }
          case 68: break;
          case 20: 
            { id+=1; return createToken(id, Token.OP_ATRIBUICAO);
            }
          case 69: break;
          case 21: 
            { id+=1; return createToken(id, Token.OP_OU);
            }
          case 70: break;
          case 22: 
            { id+=1; return createToken(id, Token.OP_MENOR_IGUAL);
            }
          case 71: break;
          case 23: 
            { id+=1; return createToken(id, Token.OP_DIFERENTE);
            }
          case 72: break;
          case 24: 
            { id+=1; return createToken(id, Token.OP_MAIOR_IGUAL);
            }
          case 73: break;
          case 25: 
            { id+=1; return createToken(id, Token.PC_SE);
            }
          case 74: break;
          case 26: 
            { id+=1; return createToken(id, Token.REAL);
            }
          case 75: break;
          case 27: 
            { id+=1; return createToken(id, Token.OP_NAO);
            }
          case 76: break;
          case 28: 
            { id+=1; return createToken(id, Token.PC_ATE);
            }
          case 77: break;
          case 29: 
            { id+=1; return createToken(id, Token.PC_FIM);
            }
          case 78: break;
          case 30: 
            { id+=1; return createToken(id, Token.PC_PARA);
            }
          case 79: break;
          case 31: 
            { id+=1; return createToken(id, Token.PC_REAL);
            }
          case 80: break;
          case 32: 
            { id+=1; return createToken(id, Token.PC_CHAR);
            }
          case 81: break;
          case 33: 
            { id+=1; return createToken(id, Token.PC_FACA);
            }
          case 82: break;
          case 34: 
            { id+=1; return createToken(id, Token.PC_LEIA);
            }
          case 83: break;
          case 35: 
            { id+=1; return createToken(id, Token.PC_ENTAO);
            }
          case 84: break;
          case 36: 
            { id+=1; return createToken(id, Token.PC_FALSO);
            }
          case 85: break;
          case 37: 
            { id+=1; return createToken(id, Token.PC_SENAO);
            }
          case 86: break;
          case 38: 
            { id+=1; return createToken(id, Token.PC_REPITA);
            }
          case 87: break;
          case 39: 
            { id+=1; return createToken(id, Token.PC_INICIO);
            }
          case 88: break;
          case 40: 
            { id+=1; return createToken(id, Token.PC_STRING);
            }
          case 89: break;
          case 41: 
            { id+=1; return createToken(id, Token.PC_ESCREVA);
            }
          case 90: break;
          case 42: 
            { id+=1; return createToken(id, Token.PC_ATE_QUE);
            }
          case 91: break;
          case 43: 
            { id+=1; return createToken(id, Token.PC_INTEIRO);
            }
          case 92: break;
          case 44: 
            { id+=1; return createToken(id, Token.PC_ENQUANTO);
            }
          case 93: break;
          case 45: 
            { id+=1; return createToken(id, Token.PC_PROGRAMA);
            }
          case 94: break;
          case 46: 
            { id+=1; return createToken(id, Token.PC_VARIAVEL);
            }
          case 95: break;
          case 47: 
            { id+=1; return createToken(id, Token.PC_BOOLEANO);
            }
          case 96: break;
          case 48: 
            { id+=1; return createToken(id, Token.PC_CONSTANTE);
            }
          case 97: break;
          case 49: 
            { id+=1; return createToken(id, Token.PC_VERDADEIRO);
            }
          case 98: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
